[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

# Sample chain configuration:
#  - Modify [chains.mainnet] to correspond to a well-known chain from https://thegraph.com/docs/en/developing/supported-networks/
#  - Provide an endpoint under "url", that you can grab from https://thegraph.market
#
# [chains.mainnet]
# protocol = "substreams"
# shard = "primary"
# provider = [
#     { label = "substreams", details = { type = "substreams", url = "mainnet.eth.streamingfast.io:443", token = "$SUBSTREAMS_API_TOKEN", features = [ "compression" ], conn_pool_size = 1 } },
# ]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = ["default"]
